version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: noteapp_api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=notesdb;Username=postgres;Password=postgres
      - Redis__Configuration=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: noteapp_frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    container_name: noteapp_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notesdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: noteapp_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: 